### ISSUE TITLE
Review needed: OTel for Beginners - The JavaScript Journey -  Ep. 1 What is OTel?

### ISSUE THREAD

**Issue by LisaHJung** [open-telemetry/sig-contributor-experience#30]
**Background**
OTel for Beginners is a YouTube series aimed to help beginners get started on their JavaScript journey. 

The target demographic is developers new to observability and OTel (including high school & college students).

This episode was intentionally designed to be rudimentary so that even a layperson can explain OTel and observability to others.

The rest of the series will be more technically driven and will have hands-on experience (see [concept roadmap](https://docs.google.com/document/d/1E4ZwR_BGpOvOSjlMpxVFWHfipDPJEqw7iLnknAx_6zs/edit?tab=t.0rl) for more details)

**Review needed**
The [deck](https://docs.google.com/presentation/d/1Y9cPVACE8yorzoSvnkTJ0_vMoLk5J2M2ExeTmTrg0qg/edit?usp=sharing) has the script in the presenter's notes section. 

_What I would like help with is for someone to read over the script and the deck and ensure there isn't any incorrect info or something that does not align with OTel's vision or messaging._ 

If you find anything, please use the comment feature on the Google slide deck. 

Please ignore **[A]** in the script - these are cues to activate animation during recording. 

**Timeline**
This episode will air in January.
To meet the release timeline, the review should be completed by **December 13th, 2024**.

Thank you so much for your help! I appreciate you!

**Comment by LisaHJung** [comment]
Hello! 

Could I have get a pair of eyes on this script? 
Looking to film this episode soon.

Thank you!

**Comment by svrnm** [comment]
@open-telemetry/sig-end-user-approvers @open-telemetry/javascript-approvers @open-telemetry/docs-approvers please take a look, if you have a few minutes and can provide feedback to @LisaHJung, thanks!

**Comment by trentm** [comment]
> The [deck](https://docs.google.com/presentation/d/1Y9cPVACE8yorzoSvnkTJ0_vMoLk5J2M2ExeTmTrg0qg/edit?usp=sharing) has the script in the presenter's notes section.

@LisaHJung That deck link is to "What is OTel?" slides that covers intro material, and doesn't (yet) get into JavaScript-specifics. Is that correct?

I work on some parts of OTel JS and was going to review for JS-related content.  I skimmed the slide notes and they look reasonable to me.

**Comment by LisaHJung** [comment]
Hey @trentm ,

You ROCK and you are absolutely correct! 

I will get into JavaScript specifics starting in episode 2 and beyond. 

I will start filming this episode. 

Thank you so much for your help!
